### ISSUE TITLE
Create sequence diagrams for key processes

### ISSUE THREAD

**Issue by Nightey3s** [MiloyBlitz/Assigment_1#22]

**Comment by lwkf** [comment]
![Image](https://github.com/user-attachments/assets/edc1bfee-987a-4752-bc17-635898595aec)
![Image](https://github.com/user-attachments/assets/875152ac-aad5-4827-b09d-71bad8b43c90)
![Image](https://github.com/user-attachments/assets/7ea9b2b1-4224-4812-96c6-aaeb535582b8)
