### ISSUE TITLE
Activity Diagram

### ISSUE THREAD

**Issue by Nightey3s** [MiloyBlitz/Assigment_1#24]

**Comment by lwkf** [comment]
![Image](https://github.com/user-attachments/assets/5f1a4bf3-4490-485d-9cf4-314a23de63c9)
![Image](https://github.com/user-attachments/assets/ab04903c-2735-4673-9049-bee8691b9427)
![Image](https://github.com/user-attachments/assets/36508fac-606c-4e3b-8d1c-50f4ac08f0f7)
